### ISSUE TITLE
Target sequence length > 100K, over comparison pipeline limit, nhmmer?

### ISSUE THREAD

**Issue by ewissel** [fannyhb/fargene#10]
I have a large fasta file that is evidently too large to use. I would like to use the provided hmm classes. Full error below. I can't tell from the documentation what `(Did you mean to use nhmmer/nhmmscan?)` indicates. should I add another parameter for `nhmmer`? (very likely I am missing something obvious here)

**input**
`fargene -i fasta/contigs.fasta  --hmm-model tet_efflux -o fargene_out_fa/tet_efflux`

**output**
```
INFO: Starting fARGene
INFO: Starting pipeline, planning to analyze 1 files
INFO: Running on 1 processes
INFO: Parsing FASTA files
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Aborted

No hits in file /home/ewissel/fasta/contigs.fasta

ERROR:root:No hits in file /home/ewissel/fasta/contigs.fasta
CRITICAL: Could not find file /home/ewissel/fargene_out_fa/tet_efflux/predictedGenes/contigs-tet_efflux-filtered.fasta
CRITICAL:fargene_analysis.fargene_analysis:Could not find file /home/ewissel/fargene_out_fa/tet_efflux/predictedGenes/contigs-tet_efflux-filtered.fasta
INFO: Done with pipeline
INFO:fargene_analysis.fargene_analysis:Done with pipeline
INFO: fARGene is done.
Total number of possible genes: 0
Total number of predicted ORFS longer than 1077.0 nt: 0
Output can be found in /home/ewissel/fargene_out_fa/tet_efflux
INFO:fargene_analysis.fargene_analysis:fARGene is done.
Total number of possible genes: 0
Total number of predicted ORFS longer than 1077.0 nt: 0
Output can be found in /home/ewissel/fargene_out_fa/tet_efflux

```

**Comment by fannyhb** [comment]
Hi,

I am not really sure what is going on here since the sequences should be automatically translated and then there shouldn't be any stretch longer than 100k. So I would think that either there is something wrong with the installation of the various tools (probably either transeq or hmmer) or there is an issue with the file contigs.fasta. Did you install fargene via conda or the setup script? Can you run fargene on the tutorial data?

Try to add the argument --store-peptides to your original command, then check in the fargene_out/tet_efflux/tmpdir if you find a file named contigs-amino.fasta and if that file looks like it should. 

/Fanny

**Comment by ewissel** [comment]
I ran with the flag. Here is the command and outptut.

Command
> fargene -i sim_dat/fasta/contigs.fasta --hmm-model tet_efflux -o fargene_out_fa/tet_efflux --store-peptides --force

Output

> INFO: Starting fARGene
> INFO: Starting pipeline, planning to analyze 1 files
> INFO: Running on 1 processes
> INFO: Parsing FASTA files
> INFO: Performing hmmsearch
> 
> No hits in file /home/ewissel/amr-benchmarking/mock_2/sim_dat/fasta/contigs.fasta
> 
> ERROR:root:No hits in file /home/ewissel/amr-benchmarking/mock_2/sim_dat/fasta/contigs.fasta
> CRITICAL: Could not find file /home/ewissel/amr-benchmarking/mock_2/fargene_out_fa/tet_efflux/predictedGenes/contigs-tet_efflux-filtered.fasta
> CRITICAL:fargene_analysis.fargene_analysis:Could not find file /home/ewissel/amr-benchmarking/mock_2/fargene_out_fa/tet_efflux/predictedGenes/contigs-tet_efflux-filtered.fasta
> INFO: Done with pipeline
> INFO:fargene_analysis.fargene_analysis:Done with pipeline
> INFO: fARGene is done.
> Total number of possible genes: 0
> Total number of predicted ORFS longer than 1077.0 nt: 0
> Output can be found in /home/ewissel/amr-benchmarking/mock_2/fargene_out_fa/tet_efflux
> INFO:fargene_analysis.fargene_analysis:fARGene is done.
> Total number of possible genes: 0
> Total number of predicted ORFS longer than 1077.0 nt: 0
> Output can be found in /home/ewissel/amr-benchmarking/mock_2/fargene_out_fa/tet_efflux

Fargene works on fastqs for all hmm-model flags. The file 'fargene_out_fa/tet_efflux/tmpdir/contigs-amino.fasta looks like this (truncated)

> NODE_1_length_643018_cov_12.726297_1
ILRQFAGLNLERIPDETTILNFRRLLEKHELAAGILAVINGSGRPRPVAAPGHHRRCNAD
QCAQFDQEQGRQARPGNAPDQEGKPVLCVTNTGQMTCAAVPKMEVGLPKSACRSGLQTTR
CCCIQKVWW*ATEEKSSLRMAGEYGEDERKQTVR*RIVMPKVLPKLRWSTGFRTSRGVTC
LRTRWQPVYRRHDLHTGFGTERENLVPDAKENDKWPTP*GRIPMLERGAELPVVAMKPL*
WRWSEGAALSGRRALPTSGDEWRELGETL*HSETHGMGRLPAGQGQPRCCRHRR*NHRRF
RAGSV*ESLQAVESDVVGVVLPASGQASRNSQGIGRHAQAGSAHGW*SCRANRGQASHRA
GAGLDLPLGLLWVPAGTISEAGGGDHA*ALLAIRLGGGV*YQGSLRSDQSWVADEGGAPA
HQGGLDTSVHRAVAGCAVRNG*RHARPTRTRHPARWSAQSPPDESVHALCLRHLDATYQP
QLPVCPLRR*CGGALPQSKASGVRDALHCFTAGCLWLDDAPGEIESRVLQGQ*PSRRLSA

I installed fargene with conda (`conda install -c conda-forge -c bioconda fargene`) with python v2.7.15.

**Comment by eperezv** [comment]
Same issue here. Any clue or solution?

**Comment by ewissel** [comment]
@eperezv did you run with fasta or fastq? I had successful runs with fastq files but not fasta files.

**Comment by eperezv** [comment]
@ewissel It was fasta (assembled DNA). I'll try on the raw reads. Thanks for sharing!

**Comment by fannyhb** [comment]
@ewissel The contigs-amino file looks like it's missing a ">" at the start of the header, does the original contig file also lack the ">" at the start of the headers? If that is the case, then that could be the issue since the programs then don't detect different sequences but treat everything as one long sequence. 

If the headers do contain ">" at the start, then it could be as you are saying that there simply arent any hits in the contigs (I know the output from fARGene is not good here when it gives an error message, should try and fix that). One of the advantages with fARGene is that you could actually detect genes when using raw reads as input, genes that have been missed in the assembly (they could for instance be located in a very variable region).

hope this helps,
Fanny

**Comment by fannyhb** [comment]
The reason for this issue is that the software HMMER has removed a functionality that fARGene has used. The solution to this is for now to install an older version of HMMER (v. 3.2 or earlier).
